export const theme = {
  colors: {
    background: 'var(--color-background)',
    surface: 'var(--color-surface)',
    surface2: 'var(--color-surface-2)',
    text: 'var(--color-text)',
    textMuted: 'var(--color-text-muted)',
    border: 'var(--color-border)',
    primary: 'var(--color-primary)',
    primaryDark: 'var(--color-primary-dark)',
    accent: 'var(--color-accent)',
    accentDark: 'var(--color-accent-dark)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    error: 'var(--color-error)',
  },
  spacing: {
    4: 'var(--space-4)',
    8: 'var(--space-8)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
    24: 'var(--space-24)',
    32: 'var(--space-32)',
    48: 'var(--space-48)',
    64: 'var(--space-64)',
    80: 'var(--space-80)',
    96: 'var(--space-96)',
    128: 'var(--space-128)',
  },
  typography: {
    fonts: {
      serif: 'var(--font-serif)',
      sans: 'var(--font-sans)',
    },
    sizes: {
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      base: 'var(--font-size-base)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
      '5xl': 'var(--font-size-5xl)',
    },
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
  },
} as const;